CREATE DATABASE IF NOT EXISTS profilee_db CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS ${PROFILEE_DB_USER}@'%' IDENTIFIED BY ${PROFILEE_DB_PASSWORD}
GRANT ALL PRIVILEGES ON profilee_db.* TO ${PROFILEE_DB_USER}@'%';
FLUSH PRIVILEGES;
